name = "unfurlify-development"
type = "javascript"
account_id = "812fe038b629cd06682a5a1ad59c427d"
workers_dev = true
kv_namespaces = [{ binding = "KEVINS", id = "e3054143621a43f2b0cd1307aef68537", preview_id = "e3054143621a43f2b0cd1307aef68537" }]
vars = { ENVIRONMENT = "development", B2_KEY_ID = "001625c41c18b010000000004" }

[dev]
port = 8001

[env.production]
name = "unfurlify"
zone_id = "3a8ea55e1e512b3e36252df9c33a3f55"
routes = ["https://unfurlify.mushroomcloud.moe/api*"]
workers_dev = false
kv_namespaces = [{ binding = "KEVINS", id = "a5c9617b77434d08b61eb93522972224" }]
vars = { ENVIRONMENT = "production", B2_KEY_ID = "001625c41c18b010000000004" }

[triggers]
crons = ["0 */20 * * *"]
